"""play_by_play_enriched

Revision ID: 63f41f9aa2dd
Revises: b01519119206
Create Date: 2021-02-22 00:01:10.190488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f41f9aa2dd'
down_revision = 'b01519119206'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        DROP TABLE IF EXISTS play_by_play_enriched;
        CREATE TABLE play_by_play_enriched (
            play_id DECIMAL NOT NULL,
            game_id VARCHAR NOT NULL,
            old_game_id DECIMAL NOT NULL,
            home_team VARCHAR NOT NULL,
            away_team VARCHAR NOT NULL,
            season_type VARCHAR NOT NULL,
            week DECIMAL NOT NULL,
            posteam VARCHAR,
            posteam_type VARCHAR,
            defteam VARCHAR,
            side_of_field VARCHAR,
            yardline_100 DECIMAL,
            game_date DATE NOT NULL,
            quarter_seconds_remaining DECIMAL,
            half_seconds_remaining DECIMAL,
            game_seconds_remaining DECIMAL,
            game_half VARCHAR NOT NULL,
            quarter_end SMALLINT NOT NULL,
            drive DECIMAL,
            sp SMALLINT NOT NULL,
            qtr DECIMAL NOT NULL,
            down DECIMAL,
            goal_to_go SMALLINT NOT NULL,
            time VARCHAR,
            yrdln VARCHAR,
            ydstogo DECIMAL NOT NULL,
            ydsnet DECIMAL,
            "desc" VARCHAR NOT NULL,
            play_type VARCHAR,
            yards_gained DECIMAL,
            shotgun SMALLINT NOT NULL,
            no_huddle SMALLINT NOT NULL,
            qb_dropback DECIMAL,
            qb_kneel SMALLINT NOT NULL,
            qb_spike SMALLINT NOT NULL,
            qb_scramble SMALLINT NOT NULL,
            pass_length VARCHAR,
            pass_location VARCHAR,
            air_yards DECIMAL,
            yards_after_catch DECIMAL,
            run_location VARCHAR,
            run_gap VARCHAR,
            field_goal_result VARCHAR,
            kick_distance DECIMAL,
            extra_point_result VARCHAR,
            two_point_conv_result VARCHAR,
            home_timeouts_remaining DECIMAL NOT NULL,
            away_timeouts_remaining DECIMAL NOT NULL,
            timeout DECIMAL,
            timeout_team VARCHAR,
            td_team VARCHAR,
            td_player_name VARCHAR,
            td_player_id VARCHAR,
            posteam_timeouts_remaining DECIMAL,
            defteam_timeouts_remaining DECIMAL,
            total_home_score DECIMAL NOT NULL,
            total_away_score DECIMAL NOT NULL,
            posteam_score DECIMAL,
            defteam_score DECIMAL,
            score_differential DECIMAL,
            posteam_score_post DECIMAL,
            defteam_score_post DECIMAL,
            score_differential_post DECIMAL,
            no_score_prob DECIMAL NOT NULL,
            opp_fg_prob DECIMAL NOT NULL,
            opp_safety_prob DECIMAL NOT NULL,
            opp_td_prob DECIMAL NOT NULL,
            fg_prob DECIMAL NOT NULL,
            safety_prob DECIMAL NOT NULL,
            td_prob DECIMAL NOT NULL,
            extra_point_prob DECIMAL NOT NULL,
            two_point_conversion_prob DECIMAL NOT NULL,
            ep DECIMAL,
            epa DECIMAL,
            total_home_epa DECIMAL NOT NULL,
            total_away_epa DECIMAL NOT NULL,
            total_home_rush_epa DECIMAL NOT NULL,
            total_away_rush_epa DECIMAL NOT NULL,
            total_home_pass_epa DECIMAL NOT NULL,
            total_away_pass_epa DECIMAL NOT NULL,
            air_epa DECIMAL,
            yac_epa DECIMAL,
            comp_air_epa DECIMAL,
            comp_yac_epa DECIMAL,
            total_home_comp_air_epa DECIMAL NOT NULL,
            total_away_comp_air_epa DECIMAL NOT NULL,
            total_home_comp_yac_epa DECIMAL NOT NULL,
            total_away_comp_yac_epa DECIMAL NOT NULL,
            total_home_raw_air_epa DECIMAL NOT NULL,
            total_away_raw_air_epa DECIMAL NOT NULL,
            total_home_raw_yac_epa DECIMAL NOT NULL,
            total_away_raw_yac_epa DECIMAL NOT NULL,
            wp DECIMAL,
            def_wp DECIMAL,
            home_wp DECIMAL,
            away_wp DECIMAL,
            wpa DECIMAL,
            vegas_wpa DECIMAL,
            vegas_home_wpa DECIMAL,
            home_wp_post DECIMAL,
            away_wp_post DECIMAL,
            vegas_wp DECIMAL,
            vegas_home_wp DECIMAL NOT NULL,
            total_home_rush_wpa DECIMAL NOT NULL,
            total_away_rush_wpa DECIMAL NOT NULL,
            total_home_pass_wpa DECIMAL NOT NULL,
            total_away_pass_wpa DECIMAL NOT NULL,
            air_wpa DECIMAL,
            yac_wpa DECIMAL,
            comp_air_wpa DECIMAL,
            comp_yac_wpa DECIMAL,
            total_home_comp_air_wpa DECIMAL NOT NULL,
            total_away_comp_air_wpa DECIMAL NOT NULL,
            total_home_comp_yac_wpa DECIMAL NOT NULL,
            total_away_comp_yac_wpa DECIMAL NOT NULL,
            total_home_raw_air_wpa DECIMAL NOT NULL,
            total_away_raw_air_wpa DECIMAL NOT NULL,
            total_home_raw_yac_wpa DECIMAL NOT NULL,
            total_away_raw_yac_wpa DECIMAL NOT NULL,
            punt_blocked DECIMAL,
            first_down_rush DECIMAL,
            first_down_pass DECIMAL,
            first_down_penalty DECIMAL,
            third_down_converted DECIMAL,
            third_down_failed DECIMAL,
            fourth_down_converted DECIMAL,
            fourth_down_failed DECIMAL,
            incomplete_pass DECIMAL,
            touchback SMALLINT NOT NULL,
            interception DECIMAL,
            punt_inside_twenty DECIMAL,
            punt_in_endzone DECIMAL,
            punt_out_of_bounds DECIMAL,
            punt_downed DECIMAL,
            punt_fair_catch DECIMAL,
            kickoff_inside_twenty DECIMAL,
            kickoff_in_endzone DECIMAL,
            kickoff_out_of_bounds DECIMAL,
            kickoff_downed DECIMAL,
            kickoff_fair_catch DECIMAL,
            fumble_forced DECIMAL,
            fumble_not_forced DECIMAL,
            fumble_out_of_bounds DECIMAL,
            solo_tackle DECIMAL,
            safety DECIMAL,
            penalty DECIMAL,
            tackled_for_loss DECIMAL,
            fumble_lost DECIMAL,
            own_kickoff_recovery DECIMAL,
            own_kickoff_recovery_td DECIMAL,
            qb_hit DECIMAL,
            rush_attempt DECIMAL,
            pass_attempt DECIMAL,
            sack DECIMAL,
            touchdown DECIMAL,
            pass_touchdown DECIMAL,
            rush_touchdown DECIMAL,
            return_touchdown DECIMAL,
            extra_point_attempt DECIMAL,
            two_point_attempt DECIMAL,
            field_goal_attempt DECIMAL,
            kickoff_attempt DECIMAL,
            punt_attempt DECIMAL,
            fumble DECIMAL,
            complete_pass DECIMAL,
            assist_tackle DECIMAL,
            lateral_reception DECIMAL,
            lateral_rush DECIMAL,
            lateral_return DECIMAL,
            lateral_recovery DECIMAL,
            passer_player_id VARCHAR,
            passer_player_name VARCHAR,
            passing_yards DECIMAL,
            receiver_player_id VARCHAR,
            receiver_player_name VARCHAR,
            receiving_yards DECIMAL,
            rusher_player_id VARCHAR,
            rusher_player_name VARCHAR,
            rushing_yards DECIMAL,
            lateral_receiver_player_id VARCHAR,
            lateral_receiver_player_name VARCHAR,
            lateral_receiving_yards DECIMAL,
            lateral_rusher_player_id VARCHAR,
            lateral_rusher_player_name VARCHAR,
            lateral_rushing_yards DECIMAL,
            lateral_sack_player_id SMALLINT,
            lateral_sack_player_name SMALLINT,
            interception_player_id VARCHAR,
            interception_player_name VARCHAR,
            lateral_interception_player_id VARCHAR,
            lateral_interception_player_name VARCHAR,
            punt_returner_player_id VARCHAR,
            punt_returner_player_name VARCHAR,
            lateral_punt_returner_player_id VARCHAR,
            lateral_punt_returner_player_name VARCHAR,
            kickoff_returner_player_name VARCHAR,
            kickoff_returner_player_id VARCHAR,
            lateral_kickoff_returner_player_id VARCHAR,
            lateral_kickoff_returner_player_name VARCHAR,
            punter_player_id VARCHAR,
            punter_player_name VARCHAR,
            kicker_player_name VARCHAR,
            kicker_player_id VARCHAR,
            own_kickoff_recovery_player_id VARCHAR,
            own_kickoff_recovery_player_name VARCHAR,
            blocked_player_id VARCHAR,
            blocked_player_name VARCHAR,
            tackle_for_loss_1_player_id VARCHAR,
            tackle_for_loss_1_player_name VARCHAR,
            tackle_for_loss_2_player_id SMALLINT,
            tackle_for_loss_2_player_name SMALLINT,
            qb_hit_1_player_id VARCHAR,
            qb_hit_1_player_name VARCHAR,
            qb_hit_2_player_id VARCHAR,
            qb_hit_2_player_name VARCHAR,
            forced_fumble_player_1_team VARCHAR,
            forced_fumble_player_1_player_id VARCHAR,
            forced_fumble_player_1_player_name VARCHAR,
            forced_fumble_player_2_team VARCHAR,
            forced_fumble_player_2_player_id VARCHAR,
            forced_fumble_player_2_player_name VARCHAR,
            solo_tackle_1_team VARCHAR,
            solo_tackle_2_team VARCHAR,
            solo_tackle_1_player_id VARCHAR,
            solo_tackle_2_player_id VARCHAR,
            solo_tackle_1_player_name VARCHAR,
            solo_tackle_2_player_name VARCHAR,
            assist_tackle_1_player_id VARCHAR,
            assist_tackle_1_player_name VARCHAR,
            assist_tackle_1_team VARCHAR,
            assist_tackle_2_player_id VARCHAR,
            assist_tackle_2_player_name VARCHAR,
            assist_tackle_2_team VARCHAR,
            assist_tackle_3_player_id SMALLINT,
            assist_tackle_3_player_name SMALLINT,
            assist_tackle_3_team SMALLINT,
            assist_tackle_4_player_id SMALLINT,
            assist_tackle_4_player_name SMALLINT,
            assist_tackle_4_team SMALLINT,
            tackle_with_assist DECIMAL,
            tackle_with_assist_1_player_id VARCHAR,
            tackle_with_assist_1_player_name VARCHAR,
            tackle_with_assist_1_team VARCHAR,
            tackle_with_assist_2_player_id SMALLINT,
            tackle_with_assist_2_player_name SMALLINT,
            tackle_with_assist_2_team SMALLINT,
            pass_defense_1_player_id VARCHAR,
            pass_defense_1_player_name VARCHAR,
            pass_defense_2_player_id VARCHAR,
            pass_defense_2_player_name VARCHAR,
            fumbled_1_team VARCHAR,
            fumbled_1_player_id VARCHAR,
            fumbled_1_player_name VARCHAR,
            fumbled_2_player_id VARCHAR,
            fumbled_2_player_name VARCHAR,
            fumbled_2_team VARCHAR,
            fumble_recovery_1_team VARCHAR,
            fumble_recovery_1_yards DECIMAL,
            fumble_recovery_1_player_id VARCHAR,
            fumble_recovery_1_player_name VARCHAR,
            fumble_recovery_2_team VARCHAR,
            fumble_recovery_2_yards DECIMAL,
            fumble_recovery_2_player_id VARCHAR,
            fumble_recovery_2_player_name VARCHAR,
            return_team VARCHAR,
            return_yards DECIMAL,
            penalty_team VARCHAR,
            penalty_player_id VARCHAR,
            penalty_player_name VARCHAR,
            penalty_yards DECIMAL,
            replay_or_challenge SMALLINT NOT NULL,
            replay_or_challenge_result VARCHAR,
            penalty_type VARCHAR,
            defensive_two_point_attempt DECIMAL,
            defensive_two_point_conv DECIMAL,
            defensive_extra_point_attempt DECIMAL,
            defensive_extra_point_conv DECIMAL,
            season DECIMAL NOT NULL,
            cp DECIMAL,
            cpoe DECIMAL,
            series DECIMAL NOT NULL,
            series_success SMALLINT NOT NULL,
            series_result VARCHAR,
            order_sequence DECIMAL NOT NULL,
            start_time VARCHAR NOT NULL,
            time_of_day VARCHAR,
            stadium VARCHAR NOT NULL,
            weather VARCHAR NOT NULL,
            nfl_api_id VARCHAR NOT NULL,
            play_clock DECIMAL NOT NULL,
            play_deleted SMALLINT NOT NULL,
            play_type_nfl VARCHAR,
            special_teams_play SMALLINT NOT NULL,
            st_play_type VARCHAR,
            end_clock_time VARCHAR,
            end_yard_line VARCHAR,
            fixed_drive DECIMAL NOT NULL,
            fixed_drive_result VARCHAR,
            drive_real_start_time SMALLINT,
            drive_play_count DECIMAL,
            drive_time_of_possession VARCHAR,
            drive_first_downs DECIMAL,
            drive_inside20 DECIMAL,
            drive_ended_with_score DECIMAL,
            drive_quarter_start DECIMAL,
            drive_quarter_end DECIMAL,
            drive_yards_penalized DECIMAL,
            drive_start_transition VARCHAR,
            drive_end_transition VARCHAR,
            drive_game_clock_start VARCHAR,
            drive_game_clock_end VARCHAR,
            drive_start_yard_line VARCHAR,
            drive_end_yard_line VARCHAR,
            drive_play_id_started DECIMAL,
            drive_play_id_ended DECIMAL,
            away_score DECIMAL NOT NULL,
            home_score DECIMAL NOT NULL,
            location VARCHAR NOT NULL,
            result DECIMAL NOT NULL,
            total DECIMAL NOT NULL,
            spread_line DECIMAL NOT NULL,
            total_line DECIMAL NOT NULL,
            div_game SMALLINT NOT NULL,
            roof VARCHAR NOT NULL,
            surface VARCHAR,
            temp DECIMAL,
            wind DECIMAL,
            home_coach VARCHAR NOT NULL,
            away_coach VARCHAR NOT NULL,
            stadium_id VARCHAR NOT NULL,
            game_stadium VARCHAR NOT NULL,
            success DECIMAL,
            passer VARCHAR,
            passer_jersey_number DECIMAL,
            rusher VARCHAR,
            rusher_jersey_number DECIMAL,
            receiver VARCHAR,
            receiver_jersey_number DECIMAL,
            pass DECIMAL,
            rush DECIMAL,
            first_down DECIMAL,
            aborted_play SMALLINT NOT NULL,
            special SMALLINT NOT NULL,
            play SMALLINT NOT NULL,
            passer_id VARCHAR,
            rusher_id VARCHAR,
            receiver_id VARCHAR,
            name VARCHAR,
            jersey_number DECIMAL,
            id VARCHAR,
            fantasy_player_name VARCHAR,
            fantasy_player_id VARCHAR,
            fantasy VARCHAR,
            fantasy_id VARCHAR,
            out_of_bounds SMALLINT NOT NULL,
            qb_epa DECIMAL,
            xyac_epa DECIMAL,
            xyac_mean_yardage DECIMAL,
            xyac_median_yardage DECIMAL,
            xyac_success DECIMAL,
            xyac_fd DECIMAL,
            xpass DECIMAL,
            pass_oe DECIMAL,
            year DECIMAL NOT NULL,
            passer_position VARCHAR,
            receiver_position VARCHAR,
            rusher_position VARCHAR
        );
    """)


def downgrade():
    op.execute("""DROP TABLE IF EXISTS play_by_play_enriched""")
